id = "rescript"
name = "ReScript"
description = "ReScript support."
version = "0.4.2"
schema_version = 1
authors = ["Karolis Narkevicius <hey@kn8.lt>"]
repository = "https://github.com/rescript-lang/rescript-zed"

[language_servers.rescript-language-server]
name = "rescript-language-server"
language = "ReScript"

[grammars.rescript]
repository = "https://github.com/rescript-lang/tree-sitter-rescript"
commit = "d2df8a285fff95de56a91d2f8152aeceb66f40ef"
